
title: Johannes Schroth
email: johannesschroth11@gmail.com
description:
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jschroth_
github_username:  JohannesSchroth

remote_theme: "jeffreytse/jekyll-theme-yat"

# Build settings

yat:
  date_format: "%b %d, %Y"

header_transparent: true

night_mode: "on"

header_pages:
  - index.html
  - archives.html
  - categories.html
  - about.html

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship

google_analytics: G-46HS9DX6GD

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
